name: flutter
description: A modified Flutter package that is needed by Flutter2jsX framework.
version: 0.0.4
homepage: https://github.com/ethanblake4

environment:
  sdk: '>2.0.0 <=3.0.0'

dependencies:
  flutter2js: any
  collection: '^1.14.3'
  http: '^0.11.3'
  intl:
  js: '^0.6.1'
  logging: '^0.11.3'
  meta: '^1.1.1'
  vector_math: '^2.0.5'

dependency_overrides:
  flutter2js:
    git:
      url: git://github.com/ethanblake4/flutter2js

dev_dependencies:
  mockito: any
  test: any