name: flutter_localizations
dependencies:
  # To update these, use "flutter update-packages --force-upgrade".

  flutter:
    sdk: flutter
  intl: '^0.15.2'

dev_dependencies:
  flutter_test:
    sdk: flutter
  test: '^0.12.26'
