name: flutter_test
dependencies:
  # To update these, use "flutter update-packages --force-upgrade".

  # We depend on very specific internal implementation details of the
  # 'test' package, which change between versions, so when upgrading
  # this, make sure the tests are still running correctly.
  test: '^0.12.26'

  # We use FakeAsync and other testing utilities.
  quiver: '^0.27.0'

  flutter: any

  # We import stack_trace because the test packages uses it and we
  # need to be able to unmangle the stack traces that it passed to
  # stack_trace. See https://github.com/dart-lang/test/issues/590
  stack_trace: '^1.9.1'

  # We override the createHttpClient in flutter with a MockClient.
  http: '^0.11.3+14'

  # Used by globalToLocal et al.
  vector_math: '^2.0.5'
